apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: malikvti/product-service:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "10.100.33.68"     # service name database di K8s
            - name: DB_PORT
              value: "1433"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: password
            - name: DB_NAME
              value: "product_demo_db"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8082
      targetPort: 8082
