server:
  port: 7070

spring:
  application:
    name: user-service

  data:
    redis:
      host: 10.100.34.246
      port: 12345

  datasource:
    url: jdbc:sqlserver://10.100.33.68:1433;databaseName=user_db_demo;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: lek
    password: P@ssw0rd

  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: GMT+7
    serialization:
      write-dates-as-timestamps: false

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: onHxm0yleYqLUcT6289RGI8tnAYxS9EY
  expiration: 86400000
