server:
  port: 6060

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: 10.100.34.246
      port: 12345

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
    config:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
